#!/usr/bin/env bash

dry_run="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "XDG_CONFIG_HOME is not set. Using ~/.config"
    XDG_CONFIG_HOME="$HOME/.config"
fi

if [ -z "$DEV_ENV" ]; then
    echo "DEV_ENV is not set. Please set DEV_ENV to continue..."
    exit 1
fi

if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY RUN]: $1"
    else
        echo "$1"
    fi
}

log "env: $DEV_ENV"

update_files() {
    log "Updating config files for $DEV_ENV environment..."
    log "Source: $1"

    pushd "$1" &> /dev/null || exit
    (
        configs=$(find . -mindepth 1 -maxdepth 1 -type d)
        for c in $configs; do
            directory=${2%/}/${c#./}

            log ">>> Removing: rm -rf $directory"

            if [[ $dry_run == "0" ]]; then
                rm -rf "$directory"
            fi

            log ">>> Copying env: cp $1/${c#./} $2"
            if [[ $dry_run == "0" ]]; then
                cp -r "./$c" "$2"
            fi
        done
    )
    popd &> /dev/null || exit
}

copy() {
    log "Removing: $2"
    if [[ $dry_run == "0" ]]; then
        rm "$2"
    fi

    log "Copying: $1 to $2"
    if [[ $dry_run == "0" ]]; then
        cp "$1" "$2"
    fi
}

update_files "$DEV_ENV/env/.config" "$XDG_CONFIG_HOME"
update_files "$DEV_ENV/env/.local" "$HOME/.local"
update_files "$DEV_ENV/env/.agents" "$HOME/.agents"

copy "$DEV_ENV/tmux-sessionizer/tmux-sessionizer" "$HOME/.local/scripts/tmux-sessionizer"
copy "$DEV_ENV/env/.zsh_profile" "$HOME/.zsh_profile"
copy "$DEV_ENV/env/.zshrc" "$HOME/.zshrc"
copy "$DEV_ENV/env/.tmux-sessionizer" "$HOME/.tmux-sessionizer"
copy "$DEV_ENV/dev-env" "$HOME/.local/scripts/dev-env"
