#!/usr/bin/env bash

git submodule init
git submodule update

pushd env/.config/nvim || exit
git checkout main
popd || exit

pushd tmux-sessionizer || exit
git checkout master
popd || exit

pushd env/.config/.ai || exit
git checkout main
popd || exit
