#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV need to be present"
    exit 1
fi

export DEV_ENV="$DEV_ENV"

grep=""
dry_run="0"

while [[ $# -gt 0 ]]; do
    case $1 in
        --grep)
            grep="$2"
            shift 2
            ;;
        --dry-run)
            dry_run="1"
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY RUN] $1"
    else
        echo "$1"
    fi
}

log "RUN: env $DEV_ENV -- grep $grep"

runs_dir=""
if [[ "$OSTYPE" == "darwin"* ]]; then
    runs_dir=$(find "$script_dir/runs" -type f -perm +111)
else
    runs_dir=$(find "$script_dir/runs" -type f -executable)
fi

for s in $runs_dir; do
    if basename "$s" | grep -vq "$grep"; then
        log "grep \"$grep\" filtered out $s"
        continue
    fi


    if [[ $dry_run == "0" ]]; then
        log "Running $s"
        $s
    fi
done

