#!/usr/bin/env bash

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd )

export DEV_ENV=$script_dir

# Initialize the script
$script_dir/init

# Install required packages with run

$script_dir/run

# Setup the environment

$script_dir/dev-env
