#!/usr/bin/env bash

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)

echo "Installing Docker for ${OS} on ${ARCH}..."

if [[ "${OS}" == "linux" ]]; then
    if [[ "${ARCH}" == "x86_64" ]]; then
        curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-20.10.7.tgz | tar xzv --strip 1 -C /usr/local/bin docker/docker
    elif [[ "${ARCH}" == "aarch64" ]]; then
        curl -fsSL https://download.docker.com/linux/static/stable/aarch64/docker-20.10.7.tgz | tar xzv --strip 1 -C /usr/local/bin docker/docker
    else
        echo "Unsupported architecture: ${ARCH}"
        exit 1
    fi
elif [[ "${OS}" == "darwin" ]]; then
    brew install docker
else
    echo "Unsupported operating system: ${OS}"
    exit 1
fi
